/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisgst.view;

import br.com.caelum.stella.validation.CPFValidator;
import br.com.caelum.stella.validation.InvalidStateException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static javax.xml.bind.DatatypeConverter.parseInteger;
import sisgst.dao.ColaboradorDao;
import sisgst.dao.EquipeDao;
import sisgst.modelo.Colaborador;
import sisgst.modelo.Equipe;
import sisgst.principal.WebServiceCep;

/**
 *
 * @author renan
 */
public class CadastroColaborador extends javax.swing.JPanel {

    /**
     * Creates new form CadastroColaborador
     */
    private List<Equipe> listaEquipe;
    public CadastroColaborador() throws SQLException {
        initComponents();
        ComboTipoColaborador.addItem("Gestor");
        ComboTipoColaborador.addItem("Colaborador");
        
      
        EquipeDao equipe = new EquipeDao();
       
       
         this.listaEquipe = equipe.listarEquipeCombo();
            

            for (int i = 0; i < listaEquipe.size(); i++) {
                Equipe e = listaEquipe.get(i);
                comboEquipe.addItem(e.getNomeEquipe());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        LabeltipoColaborador = new javax.swing.JLabel();
        LabelCadastroColaborador = new javax.swing.JLabel();
        ComboTipoColaborador = new javax.swing.JComboBox<>();
        LabelNome = new javax.swing.JLabel();
        cpNome = new javax.swing.JTextField();
        LabelIdade = new javax.swing.JLabel();
        cpIdade = new javax.swing.JTextField();
        LabelCPF = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        cpEmail = new javax.swing.JTextField();
        LabelCelular = new javax.swing.JLabel();
        cpCelular = new javax.swing.JFormattedTextField();
        cpCPF = new javax.swing.JFormattedTextField();
        LabelUsuario = new javax.swing.JLabel();
        LabelSenha = new javax.swing.JLabel();
        cpUsuario = new javax.swing.JTextField();
        cpSenha = new javax.swing.JTextField();
        LabelDadosColaborador = new javax.swing.JLabel();
        LabelEnderecoColaborador = new javax.swing.JLabel();
        LabelRua = new javax.swing.JLabel();
        LabelBairro = new javax.swing.JLabel();
        LabelCidade = new javax.swing.JLabel();
        LabelComplemento = new javax.swing.JLabel();
        cpRua = new javax.swing.JTextField();
        cpComplemento = new javax.swing.JTextField();
        cpBairro = new javax.swing.JTextField();
        cpCidade = new javax.swing.JTextField();
        LabelCEP = new javax.swing.JLabel();
        cpCEP = new javax.swing.JFormattedTextField();
        LabelEquipe = new javax.swing.JLabel();
        BotaoCadastrar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        comboEquipe = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        LabeltipoColaborador.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabeltipoColaborador.setText("Tipo do Colaborador:");

        LabelCadastroColaborador.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        LabelCadastroColaborador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCadastroColaborador.setText("Cadastro Colaborador");

        ComboTipoColaborador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Selecione"}));
        ComboTipoColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTipoColaboradorActionPerformed(evt);
            }
        });

        LabelNome.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelNome.setText("Nome:");

        LabelIdade.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelIdade.setText("Idade:");

        cpIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpIdadeActionPerformed(evt);
            }
        });

        LabelCPF.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelCPF.setText("CPF:");

        LabelEmail.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelEmail.setText("E-mail:");

        cpEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpEmailActionPerformed(evt);
            }
        });

        LabelCelular.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelCelular.setText("Celular:");

        try {
            cpCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cpCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpCPFActionPerformed(evt);
            }
        });

        LabelUsuario.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelUsuario.setText("Usuário:");

        LabelSenha.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelSenha.setText("Senha:");

        LabelDadosColaborador.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        LabelDadosColaborador.setText("Dados Colaborador:");

        LabelEnderecoColaborador.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        LabelEnderecoColaborador.setText("Endereço Colaborador:");

        LabelRua.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelRua.setText("Rua:");

        LabelBairro.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelBairro.setText("Bairro:");

        LabelCidade.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelCidade.setText("Cidade");

        LabelComplemento.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelComplemento.setText("Complemento:");

        LabelCEP.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelCEP.setText("CEP:");

        try {
            cpCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LabelEquipe.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        LabelEquipe.setText("Equipe:");

        BotaoCadastrar.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        BotaoCadastrar.setText("Cadastrar");
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });

        comboEquipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a equipe" }));

        jButton1.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jButton1.setText("BUSCAR CEP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelBairro)
                            .addComponent(LabelCidade)
                            .addComponent(LabelRua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cpBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpCidade)
                            .addComponent(cpRua, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoCadastrar))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelComplemento)
                            .addComponent(LabelCEP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCadastroColaborador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelNome)
                                        .addGap(18, 18, 18)
                                        .addComponent(cpNome))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabeltipoColaborador)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ComboTipoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(LabelEmail)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cpEmail))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(LabelIdade)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cpIdade)))
                                        .addGap(1, 1, 1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LabelCPF)
                                        .addGap(25, 25, 25)
                                        .addComponent(cpCPF)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelCelular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpCelular))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelEquipe)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LabelUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(LabelSenha)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cpSenha)
                                            .addComponent(cpUsuario)
                                            .addComponent(comboEquipe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelDadosColaborador)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelEnderecoColaborador)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addComponent(jSeparator3)
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelCadastroColaborador)
                .addGap(5, 5, 5)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelDadosColaborador)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNome)
                    .addComponent(cpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCelular)
                    .addComponent(cpCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIdade)
                    .addComponent(cpIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelUsuario)
                    .addComponent(cpUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabeltipoColaborador)
                    .addComponent(ComboTipoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSenha)
                    .addComponent(cpSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCPF)
                    .addComponent(cpCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEquipe)
                    .addComponent(comboEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmail)
                    .addComponent(cpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(LabelEnderecoColaborador)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRua)
                    .addComponent(cpRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCEP)
                    .addComponent(cpCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBairro)
                    .addComponent(cpBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelComplemento)
                    .addComponent(cpComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCidade)
                    .addComponent(cpCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(BotaoCadastrar)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboTipoColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTipoColaboradorActionPerformed
        
    }//GEN-LAST:event_ComboTipoColaboradorActionPerformed

    private void cpIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpIdadeActionPerformed

    private void cpCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpCPFActionPerformed

    private void cpEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpEmailActionPerformed

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        buscaCep();
        if(ValidarDados()){
        Colaborador co = new Colaborador();
        co.setNomeColaborador(cpNome.getText());
        co.setIdadeColaborador(cpIdade.getText());
        co.setTipoColaborador(ComboTipoColaborador.getSelectedItem().toString());
        co.setEmailColaborador(cpEmail.getText());
        co.setCelularColaborador(cpCelular.getText());
        co.setUsuarioColaborador(cpUsuario.getText());
        co.setSenhaColaborador(cpSenha.getText());
        Equipe e = this.listaEquipe.get(comboEquipe.getSelectedIndex());
        co.setEquipeColabarador(e.getIdEquipe());
        co.setRuaColaborador(cpRua.getText());
        co.setBairroColaborador(cpBairro.getText());
        co.setCidadeColaborador(cpCidade.getText());
        co.setComplementoColaborador(cpComplemento.getText());
        co.setCpfColaborador(cpCPF.getText());
        String cep = cpCEP.getText();
        cep = cep.replaceAll("[^0-9]", "");
        co.setCepColaborador((cep));
        
        ColaboradorDao CoDao = new ColaboradorDao();
        try {
            CoDao.inserir(co);
            JOptionPane.showMessageDialog(null, "Cliente inserido com sucesso !");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha ao inserir cliente !");
            Logger.getLogger(CadastroColaborador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        }
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        buscaCep();
    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean ValidarDados() {
       CPFValidator validator = new CPFValidator();

       try {

           validator.assertValid(cpCPF.getText());
           String Nome = cpNome.getText();
           String Idade = cpIdade.getText();
           String Cel = cpCelular.getText();
           String Usu = cpUsuario.getText();
           String Senha = cpSenha.getText();
           String TipoColaborador = ComboTipoColaborador.getSelectedItem().toString();
           String Equipe = comboEquipe.getSelectedItem().toString();
           String Email = cpEmail.getText();

           if (Nome.isEmpty() || Nome.trim().equals("")) {
               JOptionPane.showMessageDialog(null, "DIGITE UM NOME VÁLIDO!");
               return false;
           } else if (Idade.isEmpty() || Idade.trim().equals("")) {
               JOptionPane.showMessageDialog(null, "INSIRA UMA IDADE");
               return false;
           } else if (Cel.equals("(  )     -    ") || Cel.length() < 11) {
               JOptionPane.showMessageDialog(null, "INFORME SEU TELEFONE PARA CONTATO");
               return false;
           } else if (Usu.isEmpty() || Usu.trim().equals("")) {
               JOptionPane.showMessageDialog(null, "INFORME UM USUÁRIO VÁLIDO!");
               return false;
           } else if (Senha.isEmpty() || Senha.trim().equals("")) {
               JOptionPane.showMessageDialog(null, "INSIRA ALGUMA SENHA PRO SEU USUÁRIO!");
               return false;
           } else if (TipoColaborador.isEmpty() || TipoColaborador.trim().equals("Selecione")) {
               JOptionPane.showMessageDialog(null, "INFORME O TIPO DO COLABORADOR!");
               return false;
           } else if (Equipe.isEmpty() || Equipe.trim().equals("Selecione a equipe")) {
               JOptionPane.showMessageDialog(null, "INFORME A EQUIPE DO COLABORADOR");  
               return false;
           } else if (Email.isEmpty() || Email.trim().equals("")) {
               JOptionPane.showMessageDialog(null, "INFORME UM E-MAIL PARA CONTATO");
               return false;
           }

       } catch (InvalidStateException e) {
JOptionPane.showMessageDialog(null, "CPF INVÁLIDO!");
           return false;
       }
       return true;
   }
    
        public void buscaCep() {
        
        WebServiceCep webServiceCep = WebServiceCep.searchCep(cpCEP.getText());
        //A ferramenta de busca ignora qualquer caracter que nao seja numero.

        //caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
            
            cpRua.setText(webServiceCep.getLogradouroFull());
            cpCidade.setText(webServiceCep.getCidade());
            cpBairro.setText(webServiceCep.getBairro());
            
            System.out.println("Cep: " + webServiceCep.getCep());
            System.out.println("Logradouro: " + webServiceCep.getLogradouroFull());
            System.out.println("Bairro: " + webServiceCep.getBairro());
            System.out.println("Cidade: "
                    + webServiceCep.getCidade() + "/" + webServiceCep.getUf());

            //caso haja problemas imprime as exce??es.
        } else {
            JOptionPane.showMessageDialog(null, "CEP INVÁLIDO!");

            
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JComboBox<String> ComboTipoColaborador;
    private javax.swing.JLabel LabelBairro;
    private javax.swing.JLabel LabelCEP;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelCadastroColaborador;
    private javax.swing.JLabel LabelCelular;
    private javax.swing.JLabel LabelCidade;
    private javax.swing.JLabel LabelComplemento;
    private javax.swing.JLabel LabelDadosColaborador;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEnderecoColaborador;
    private javax.swing.JLabel LabelEquipe;
    private javax.swing.JLabel LabelIdade;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelRua;
    private javax.swing.JLabel LabelSenha;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel LabeltipoColaborador;
    private javax.swing.JComboBox<String> comboEquipe;
    private javax.swing.JTextField cpBairro;
    private javax.swing.JFormattedTextField cpCEP;
    private javax.swing.JFormattedTextField cpCPF;
    private javax.swing.JFormattedTextField cpCelular;
    private javax.swing.JTextField cpCidade;
    private javax.swing.JTextField cpComplemento;
    private javax.swing.JTextField cpEmail;
    private javax.swing.JTextField cpIdade;
    private javax.swing.JTextField cpNome;
    private javax.swing.JTextField cpRua;
    private javax.swing.JTextField cpSenha;
    private javax.swing.JTextField cpUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
