/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisgst.view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sisgst.dao.AgendaDao;
import sisgst.dao.ColaboradorDao;
import sisgst.dao.EquipeDao;
import sisgst.modelo.Agenda;
import sisgst.modelo.Colaborador;
import sisgst.modelo.Equipe;

/**
 *
 * @author Cristian
 */
public class telaAgenda extends javax.swing.JPanel {
private List<Equipe> listaEquipe;
private List<Colaborador> listaColaborador;
private boolean radioAux = true;
    /**
     * Creates new form Agenda
     * @throws java.sql.SQLException
     */
    public telaAgenda() throws SQLException {
        initComponents();
        
                EquipeDao equipe = new EquipeDao();
              this.listaEquipe = equipe.listarEquipeCombo();
            

            for (int i = 0; i < listaEquipe.size(); i++) {
                Equipe e = listaEquipe.get(i);
                comboEquipe.addItem(e.getNomeEquipe());
            }
            ColaboradorDao colaborador = new ColaboradorDao();
            this.listaColaborador = colaborador.listarColaboradorCombo();
            for (int i = 0; i < listaColaborador.size(); i++) {
                Colaborador co = listaColaborador.get(i);
                comboColaborador.addItem(co.getNomeColaborador());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoes = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataAgenda = new javax.swing.JFormattedTextField();
        tituloAgenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoAgenda = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        botaoCadastrarTarefa = new javax.swing.JButton();
        comboEquipe = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboColaborador = new javax.swing.JComboBox<>();
        radioEquipe = new javax.swing.JRadioButton();
        radioColaborador = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setText("      AGENDA");

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("Data do compromisso");

        try {
            dataAgenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("Titulo Tarefa");

        descricaoAgenda.setColumns(20);
        descricaoAgenda.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        descricaoAgenda.setRows(5);
        jScrollPane1.setViewportView(descricaoAgenda);

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("Descrição Tarefa");

        botaoCadastrarTarefa.setText("Cadastrar Tarefa");
        botaoCadastrarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarTarefaActionPerformed(evt);
            }
        });

        comboEquipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        comboEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEquipeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("Selecione a Equipe");

        comboColaborador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        comboColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColaboradorActionPerformed(evt);
            }
        });

        botoes.add(radioEquipe);
        radioEquipe.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioEquipeStateChanged(evt);
            }
        });
        radioEquipe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioEquipeMouseClicked(evt);
            }
        });
        radioEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEquipeActionPerformed(evt);
            }
        });

        botoes.add(radioColaborador);
        radioColaborador.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioColaboradorStateChanged(evt);
            }
        });
        radioColaborador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioColaboradorMouseClicked(evt);
            }
        });
        radioColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioColaboradorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("Selecione o Colaborador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoCadastrarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioEquipe)
                            .addComponent(radioColaborador)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(dataAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(tituloAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(comboEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(radioEquipe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tituloAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(radioColaborador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoCadastrarTarefa)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarTarefaActionPerformed
       Agenda A = new Agenda();
       A.setDataCompromissoAgenda(dataAgenda.getText());
       A.setTituloAgenda(tituloAgenda.getText());
       A.setDescricaoAgenda(descricaoAgenda.getText());
       
       if(this.radioColaborador.isSelected() == radioAux){
       Equipe e = this.listaEquipe.get(comboEquipe.getSelectedIndex());
       A.setCodigoEquipeAgenda(0);
       }else{
        Equipe e = this.listaEquipe.get(comboEquipe.getSelectedIndex());
       A.setCodigoEquipeAgenda(e.getIdEquipe());
       }
      
       if(this.radioEquipe.isSelected() == radioAux){
       Colaborador co = this.listaColaborador.get(comboColaborador.getSelectedIndex());
       A.setCodigoColaboradorAgenda(0);
       }else{
       Colaborador co = this.listaColaborador.get(comboColaborador.getSelectedIndex());
       A.setCodigoColaboradorAgenda(co.getIdColaborador());
       }
       
       
       AgendaDao Ag = new AgendaDao();
        try {
            Ag.inserir(A);
            JOptionPane.showMessageDialog(null, "Tarefa inserida com sucesso !");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha ao inserir tarefa !");
            Logger.getLogger(CadastroColaborador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoCadastrarTarefaActionPerformed

    private void comboEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEquipeActionPerformed

    private void comboColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColaboradorActionPerformed

    }//GEN-LAST:event_comboColaboradorActionPerformed

    private void radioEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEquipeActionPerformed

    }//GEN-LAST:event_radioEquipeActionPerformed

    private void radioColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioColaboradorActionPerformed
        
       
    }//GEN-LAST:event_radioColaboradorActionPerformed

    private void radioEquipeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioEquipeMouseClicked
     
    }//GEN-LAST:event_radioEquipeMouseClicked

    private void radioColaboradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioColaboradorMouseClicked

              
    }//GEN-LAST:event_radioColaboradorMouseClicked

    private void radioEquipeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioEquipeStateChanged
        
        if(radioEquipe.isSelected()== radioAux){
            this.comboColaborador.setEnabled(false);
            this.comboEquipe.setEnabled(true);
        }
    }//GEN-LAST:event_radioEquipeStateChanged

    private void radioColaboradorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioColaboradorStateChanged

        if(radioColaborador.isSelected()== radioAux){
            this.comboEquipe.setEnabled(false);
            this.comboColaborador.setEnabled(true);
        }
    }//GEN-LAST:event_radioColaboradorStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrarTarefa;
    private javax.swing.ButtonGroup botoes;
    private javax.swing.JComboBox<String> comboColaborador;
    private javax.swing.JComboBox<String> comboEquipe;
    private javax.swing.JFormattedTextField dataAgenda;
    private javax.swing.JTextArea descricaoAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioColaborador;
    private javax.swing.JRadioButton radioEquipe;
    private javax.swing.JTextField tituloAgenda;
    // End of variables declaration//GEN-END:variables
}
